/**
 * IRCTest.java
 *
 * This file was generated by XMLSpy 2008r2sp2 Enterprise Edition.
 *
 * YOU SHOULD NOT MODIFY THIS FILE, BECAUSE IT WILL BE
 * OVERWRITTEN WHEN YOU RE-RUN CODE GENERATION.
 *
 * Refer to the XMLSpy Documentation for further details.
 * http://www.altova.com/xmlspy
 */


package com.IRCTest;

import com.altova.*;
import com.altova.types.*;
import com.IRC.*;

public class IRCTest {
	protected static void example() throws Exception {
			//
			// TODO:
			//   Insert your code here...
			//
			// Example code to create and save a structure:
			//   com.IRC.IRC2 doc = com.IRC.IRC2.createDocument();			
			//   com.IRC.VIRCType root = doc.VIRC.append();
			//   ...
			//   doc.saveToFile("IRC1.xml", true);
			//
			// Example code to load and save a structure:
			//   com.IRC.IRC2 doc = com.IRC.IRC2.loadFromFile("IRC1.xml");
			//   com.IRC.VIRCType root = doc.VIRC.first();
			//   ...
			//   doc.saveToFile("IRC1.xml", true);


}

	public static void main(String args[]) {
		try {
			System.out.println("IRC Test Application");
			example();
			System.out.println("OK");
			System.exit(0);
		} catch (Exception e) {
			e.printStackTrace();
			System.exit(1);
		}
	}
}
