/**
 * SourceInstanceUnavailableException.java
 *
 * This file was generated by XMLSpy 2009 Enterprise Edition.
 *
 * YOU SHOULD NOT MODIFY THIS FILE, BECAUSE IT WILL BE
 * OVERWRITTEN WHEN YOU RE-RUN CODE GENERATION.
 *
 * Refer to the XMLSpy Documentation for further details.
 * http://www.altova.com/xmlspy
 */


package com.altova;


public class SourceInstanceUnavailableException extends RuntimeException {

	public SourceInstanceUnavailableException(String text)
	{
		super(text);
	}

	public SourceInstanceUnavailableException(String text, Throwable other)
	{
		super(text, other);
	}

}
