////////////////////////////////////////////////////////////////////////
//
// StatType.java
//
// This file was generated by XMLSpy 2008r2sp2 Enterprise Edition.
//
// YOU SHOULD NOT MODIFY THIS FILE, BECAUSE IT WILL BE
// OVERWRITTEN WHEN YOU RE-RUN CODE GENERATION.
//
// Refer to the XMLSpy Documentation for further details.
// http://www.altova.com/xmlspy
//
////////////////////////////////////////////////////////////////////////

package com.IRC;


public class StatType extends com.altova.xml.TypeBase
{
		public static com.altova.xml.meta.ComplexType getStaticInfo() { return new com.altova.xml.meta.ComplexType(com.IRC.IRC_TypeInfo.binder.getTypes()[com.IRC.IRC_TypeInfo._altova_ti_altova_StatType]); }
	
	public StatType(org.w3c.dom.Node init)
	{
		super(init);
		instantiateMembers();
	}
	
	private void instantiateMembers()
	{

		Msg= new MemberElement_Msg (this, com.IRC.IRC_TypeInfo.binder.getMembers()[com.IRC.IRC_TypeInfo._altova_mi_altova_StatType._Msg]);
		Code= new MemberElement_Code (this, com.IRC.IRC_TypeInfo.binder.getMembers()[com.IRC.IRC_TypeInfo._altova_mi_altova_StatType._Code]);
	}
	// Attributes


	// Elements
	
	public MemberElement_Msg Msg;

		public static class MemberElement_Msg
		{
			public static class MemberElement_Msg_Iterator implements java.util.Iterator
			{
				private org.w3c.dom.Node nextNode;
				private MemberElement_Msg member;
				public MemberElement_Msg_Iterator(MemberElement_Msg member) {this.member=member; nextNode=member.owner.getElementFirst(member.info);}
				public boolean hasNext() 
				{
					while (nextNode != null)
					{
						if (com.altova.xml.TypeBase.memberEqualsNode(member.info, nextNode))
							return true;
						nextNode = nextNode.getNextSibling();
					}
					return false;
				}
				
				public Object next()
				{
					com.IRC.xs.stringType nx = new com.IRC.xs.stringType(nextNode);
					nextNode = nextNode.getNextSibling();
					return nx;
				}
				
				public void remove () {}
			}
			protected com.altova.xml.TypeBase owner;
			protected com.altova.typeinfo.MemberInfo info;
			public MemberElement_Msg (com.altova.xml.TypeBase owner, com.altova.typeinfo.MemberInfo info) { this.owner = owner; this.info = info;}
			public com.IRC.xs.stringType at(int index) {return new com.IRC.xs.stringType(owner.getElementAt(info, index));}
			public com.IRC.xs.stringType first() {return new com.IRC.xs.stringType(owner.getElementFirst(info));}
			public com.IRC.xs.stringType last(){return new com.IRC.xs.stringType(owner.getElementLast(info));}
			public com.IRC.xs.stringType append(){return new com.IRC.xs.stringType(owner.createElement(info));}
			public boolean exists() {return count() > 0;}
			public int count() {return owner.countElement(info);}
			public void remove() {owner.removeElement(info);}
			public void removeAt(int index) {owner.removeElementAt(info, index);}
			public java.util.Iterator iterator() {return new MemberElement_Msg_Iterator(this);}
			public com.altova.xml.meta.Element getInfo() { return new com.altova.xml.meta.Element(info); }
		}
	
	public MemberElement_Code Code;

		public static class MemberElement_Code
		{
			public static class MemberElement_Code_Iterator implements java.util.Iterator
			{
				private org.w3c.dom.Node nextNode;
				private MemberElement_Code member;
				public MemberElement_Code_Iterator(MemberElement_Code member) {this.member=member; nextNode=member.owner.getElementFirst(member.info);}
				public boolean hasNext() 
				{
					while (nextNode != null)
					{
						if (com.altova.xml.TypeBase.memberEqualsNode(member.info, nextNode))
							return true;
						nextNode = nextNode.getNextSibling();
					}
					return false;
				}
				
				public Object next()
				{
					com.IRC.xs.unsignedIntType nx = new com.IRC.xs.unsignedIntType(nextNode);
					nextNode = nextNode.getNextSibling();
					return nx;
				}
				
				public void remove () {}
			}
			protected com.altova.xml.TypeBase owner;
			protected com.altova.typeinfo.MemberInfo info;
			public MemberElement_Code (com.altova.xml.TypeBase owner, com.altova.typeinfo.MemberInfo info) { this.owner = owner; this.info = info;}
			public com.IRC.xs.unsignedIntType at(int index) {return new com.IRC.xs.unsignedIntType(owner.getElementAt(info, index));}
			public com.IRC.xs.unsignedIntType first() {return new com.IRC.xs.unsignedIntType(owner.getElementFirst(info));}
			public com.IRC.xs.unsignedIntType last(){return new com.IRC.xs.unsignedIntType(owner.getElementLast(info));}
			public com.IRC.xs.unsignedIntType append(){return new com.IRC.xs.unsignedIntType(owner.createElement(info));}
			public boolean exists() {return count() > 0;}
			public int count() {return owner.countElement(info);}
			public void remove() {owner.removeElement(info);}
			public void removeAt(int index) {owner.removeElementAt(info, index);}
			public java.util.Iterator iterator() {return new MemberElement_Code_Iterator(this);}
			public com.altova.xml.meta.Element getInfo() { return new com.altova.xml.meta.Element(info); }
		}
}
