////////////////////////////////////////////////////////////////////////
//
// IRC_typeinfo.java
//
// This file was generated by XMLSpy 2009 Enterprise Edition.
//
// YOU SHOULD NOT MODIFY THIS FILE, BECAUSE IT WILL BE
// OVERWRITTEN WHEN YOU RE-RUN CODE GENERATION.
//
// Refer to the XMLSpy Documentation for further details.
// http://www.altova.com/xmlspy
//
////////////////////////////////////////////////////////////////////////


package com.IRC;

import com.altova.typeinfo.*;



public class IRC_TypeInfo
{
	// namespaces indices
	public static final int _altova_ni = 0;
	public static final int _altova_ni_xs = 1;


	// typeinfo indices
	public static final int _altova_tif = 0 ;
	public static final int _altova_ti_altova_ChannelClass = _altova_tif ;
	public static final int _altova_ti_altova_UserClass = 1 ;
	public static final int _altova_ti_altova_IRC2 = 2 ;
	public static final int _altova_ti_altova_VIRCType = 3 ;
	public static final int _altova_ti_altova_CmdType = 4 ;
	public static final int _altova_ti_altova_CmdType2 = 5 ;
	public static final int _altova_ti_altova_ChansType = 6 ;
	public static final int _altova_ti_altova_ServerType = 7 ;
	public static final int _altova_ti_altova_UsersType = 8 ;
	public static final int _altova_ti_altova_StatType = 9 ;
	public static final int _altova_ti_altova_NameType = 10 ;
	public static final int _altova_ti_altova_NameType2 = 11 ;
	public static final int _altova_ti_altova_ModeType = 12 ;
	public static final int _altova_ti_altova_ModeType2 = 13 ;
	public static final int _altova_ti_altova_NickType = 14 ;
	public static final int _altova_ti_altova_NickType2 = 15 ;
	public static final int _altova_til = 16 ;

	public static final int _altova_tif_xs = _altova_til;
	public static final int _altova_ti_xs_altova_ENTITIES = _altova_tif_xs ;
	public static final int _altova_ti_xs_altova_ENTITY = 17 ;
	public static final int _altova_ti_xs_altova_ID = 18 ;
	public static final int _altova_ti_xs_altova_IDREF = 19 ;
	public static final int _altova_ti_xs_altova_IDREFS = 20 ;
	public static final int _altova_ti_xs_altova_NCName = 21 ;
	public static final int _altova_ti_xs_altova_NMTOKEN = 22 ;
	public static final int _altova_ti_xs_altova_NMTOKENS = 23 ;
	public static final int _altova_ti_xs_altova_NOTATION = 24 ;
	public static final int _altova_ti_xs_altova_Name = 25 ;
	public static final int _altova_ti_xs_altova_QName = 26 ;
	public static final int _altova_ti_xs_altova_anySimpleType = 27 ;
	public static final int _altova_ti_xs_altova_anyType = 28 ;
	public static final int _altova_ti_xs_altova_anyURI = 29 ;
	public static final int _altova_ti_xs_altova_base64Binary = 30 ;
	public static final int _altova_ti_xs_altova_boolean2 = 31 ;
	public static final int _altova_ti_xs_altova_byte2 = 32 ;
	public static final int _altova_ti_xs_altova_date = 33 ;
	public static final int _altova_ti_xs_altova_dateTime = 34 ;
	public static final int _altova_ti_xs_altova_decimal = 35 ;
	public static final int _altova_ti_xs_altova_double2 = 36 ;
	public static final int _altova_ti_xs_altova_duration = 37 ;
	public static final int _altova_ti_xs_altova_float2 = 38 ;
	public static final int _altova_ti_xs_altova_gDay = 39 ;
	public static final int _altova_ti_xs_altova_gMonth = 40 ;
	public static final int _altova_ti_xs_altova_gMonthDay = 41 ;
	public static final int _altova_ti_xs_altova_gYear = 42 ;
	public static final int _altova_ti_xs_altova_gYearMonth = 43 ;
	public static final int _altova_ti_xs_altova_hexBinary = 44 ;
	public static final int _altova_ti_xs_altova_int2 = 45 ;
	public static final int _altova_ti_xs_altova_integer = 46 ;
	public static final int _altova_ti_xs_altova_language = 47 ;
	public static final int _altova_ti_xs_altova_long2 = 48 ;
	public static final int _altova_ti_xs_altova_negativeInteger = 49 ;
	public static final int _altova_ti_xs_altova_nonNegativeInteger = 50 ;
	public static final int _altova_ti_xs_altova_nonPositiveInteger = 51 ;
	public static final int _altova_ti_xs_altova_normalizedString = 52 ;
	public static final int _altova_ti_xs_altova_positiveInteger = 53 ;
	public static final int _altova_ti_xs_altova_short2 = 54 ;
	public static final int _altova_ti_xs_altova_string2 = 55 ;
	public static final int _altova_ti_xs_altova_time = 56 ;
	public static final int _altova_ti_xs_altova_token = 57 ;
	public static final int _altova_ti_xs_altova_unsignedByte = 58 ;
	public static final int _altova_ti_xs_altova_unsignedInt = 59 ;
	public static final int _altova_ti_xs_altova_unsignedLong = 60 ;
	public static final int _altova_ti_xs_altova_unsignedShort = 61 ;
	public static final int _altova_ti_xs_altova_stringType = 62 ;
	public static final int _altova_ti_xs_altova_unsignedIntType = 63 ;
	public static final int _altova_til_xs = 64 ;



	// memberinfo indices

	public static class _altova_mi_altova_ChannelClass {
		public static final int begin = 0 ;
		public static final int _Name = _altova_mi_altova_ChannelClass.begin ;
		public static final int _Desc = 1 ;
		public static final int _Mode = 2 ;
		public static final int end = 3 ;
	};


	public static class _altova_mi_altova_UserClass {
		public static final int begin = _altova_mi_altova_ChannelClass.end ;
		public static final int _Nick = _altova_mi_altova_UserClass.begin ;
		public static final int _IP = 4 ;
		public static final int _Name = 5 ;
		public static final int _Pass = 6 ;
		public static final int end = 7 ;
	};


	public static class _altova_mi_altova_IRC2 {
		public static final int begin = _altova_mi_altova_UserClass.end ;
		public static final int _VIRC = _altova_mi_altova_IRC2.begin ;
		public static final int end = 8 ;
	};


	public static class _altova_mi_altova_VIRCType {
		public static final int begin = _altova_mi_altova_IRC2.end ;
		public static final int _ID = _altova_mi_altova_VIRCType.begin ;
		public static final int _Version = 9 ;
		public static final int _Cmd = 10 ;
		public static final int _Chans = 11 ;
		public static final int _Server = 12 ;
		public static final int _Users = 13 ;
		public static final int _Stat = 14 ;
		public static final int end = 15 ;
	};


	public static class _altova_mi_altova_CmdType {
		public static final int begin = _altova_mi_altova_VIRCType.end ;
		public static final int _unnamed = _altova_mi_altova_CmdType.begin ;
		public static final int end = 16 ;
	};


	public static class _altova_mi_altova_CmdType2 {
		public static final int begin = _altova_mi_altova_CmdType.end ;
		public static final int end = _altova_mi_altova_CmdType2.begin ;
	};


	public static class _altova_mi_altova_ChansType {
		public static final int begin = _altova_mi_altova_CmdType2.end ;
		public static final int _Chan = _altova_mi_altova_ChansType.begin ;
		public static final int end = 17 ;
	};


	public static class _altova_mi_altova_ServerType {
		public static final int begin = _altova_mi_altova_ChansType.end ;
		public static final int _IP = _altova_mi_altova_ServerType.begin ;
		public static final int end = 18 ;
	};


	public static class _altova_mi_altova_UsersType {
		public static final int begin = _altova_mi_altova_ServerType.end ;
		public static final int _User = _altova_mi_altova_UsersType.begin ;
		public static final int end = 19 ;
	};


	public static class _altova_mi_altova_StatType {
		public static final int begin = _altova_mi_altova_UsersType.end ;
		public static final int _Msg = _altova_mi_altova_StatType.begin ;
		public static final int _Code = 20 ;
		public static final int end = 21 ;
	};


	public static class _altova_mi_altova_NameType {
		public static final int begin = _altova_mi_altova_StatType.end ;
		public static final int _unnamed = _altova_mi_altova_NameType.begin ;
		public static final int end = 22 ;
	};


	public static class _altova_mi_altova_NameType2 {
		public static final int begin = _altova_mi_altova_NameType.end ;
		public static final int end = _altova_mi_altova_NameType2.begin ;
	};


	public static class _altova_mi_altova_ModeType {
		public static final int begin = _altova_mi_altova_NameType2.end ;
		public static final int _unnamed = _altova_mi_altova_ModeType.begin ;
		public static final int end = 23 ;
	};


	public static class _altova_mi_altova_ModeType2 {
		public static final int begin = _altova_mi_altova_ModeType.end ;
		public static final int end = _altova_mi_altova_ModeType2.begin ;
	};


	public static class _altova_mi_altova_NickType {
		public static final int begin = _altova_mi_altova_ModeType2.end ;
		public static final int _unnamed = _altova_mi_altova_NickType.begin ;
		public static final int end = 24 ;
	};


	public static class _altova_mi_altova_NickType2 {
		public static final int begin = _altova_mi_altova_NickType.end ;
		public static final int end = _altova_mi_altova_NickType2.begin ;
	};


	public static class _altova_mi_xs_altova_ENTITIES {
		public static final int begin = _altova_mi_altova_NickType2.end ;
		public static final int end = _altova_mi_xs_altova_ENTITIES.begin ;
	};


	public static class _altova_mi_xs_altova_ENTITY {
		public static final int begin = _altova_mi_xs_altova_ENTITIES.end ;
		public static final int end = _altova_mi_xs_altova_ENTITY.begin ;
	};


	public static class _altova_mi_xs_altova_ID {
		public static final int begin = _altova_mi_xs_altova_ENTITY.end ;
		public static final int end = _altova_mi_xs_altova_ID.begin ;
	};


	public static class _altova_mi_xs_altova_IDREF {
		public static final int begin = _altova_mi_xs_altova_ID.end ;
		public static final int end = _altova_mi_xs_altova_IDREF.begin ;
	};


	public static class _altova_mi_xs_altova_IDREFS {
		public static final int begin = _altova_mi_xs_altova_IDREF.end ;
		public static final int end = _altova_mi_xs_altova_IDREFS.begin ;
	};


	public static class _altova_mi_xs_altova_NCName {
		public static final int begin = _altova_mi_xs_altova_IDREFS.end ;
		public static final int end = _altova_mi_xs_altova_NCName.begin ;
	};


	public static class _altova_mi_xs_altova_NMTOKEN {
		public static final int begin = _altova_mi_xs_altova_NCName.end ;
		public static final int end = _altova_mi_xs_altova_NMTOKEN.begin ;
	};


	public static class _altova_mi_xs_altova_NMTOKENS {
		public static final int begin = _altova_mi_xs_altova_NMTOKEN.end ;
		public static final int end = _altova_mi_xs_altova_NMTOKENS.begin ;
	};


	public static class _altova_mi_xs_altova_NOTATION {
		public static final int begin = _altova_mi_xs_altova_NMTOKENS.end ;
		public static final int end = _altova_mi_xs_altova_NOTATION.begin ;
	};


	public static class _altova_mi_xs_altova_Name {
		public static final int begin = _altova_mi_xs_altova_NOTATION.end ;
		public static final int end = _altova_mi_xs_altova_Name.begin ;
	};


	public static class _altova_mi_xs_altova_QName {
		public static final int begin = _altova_mi_xs_altova_Name.end ;
		public static final int end = _altova_mi_xs_altova_QName.begin ;
	};


	public static class _altova_mi_xs_altova_anySimpleType {
		public static final int begin = _altova_mi_xs_altova_QName.end ;
		public static final int end = _altova_mi_xs_altova_anySimpleType.begin ;
	};


	public static class _altova_mi_xs_altova_anyType {
		public static final int begin = _altova_mi_xs_altova_anySimpleType.end ;
		public static final int _unnamed = _altova_mi_xs_altova_anyType.begin ;
		public static final int end = 25 ;
	};


	public static class _altova_mi_xs_altova_anyURI {
		public static final int begin = _altova_mi_xs_altova_anyType.end ;
		public static final int end = _altova_mi_xs_altova_anyURI.begin ;
	};


	public static class _altova_mi_xs_altova_base64Binary {
		public static final int begin = _altova_mi_xs_altova_anyURI.end ;
		public static final int end = _altova_mi_xs_altova_base64Binary.begin ;
	};


	public static class _altova_mi_xs_altova_boolean2 {
		public static final int begin = _altova_mi_xs_altova_base64Binary.end ;
		public static final int end = _altova_mi_xs_altova_boolean2.begin ;
	};


	public static class _altova_mi_xs_altova_byte2 {
		public static final int begin = _altova_mi_xs_altova_boolean2.end ;
		public static final int end = _altova_mi_xs_altova_byte2.begin ;
	};


	public static class _altova_mi_xs_altova_date {
		public static final int begin = _altova_mi_xs_altova_byte2.end ;
		public static final int end = _altova_mi_xs_altova_date.begin ;
	};


	public static class _altova_mi_xs_altova_dateTime {
		public static final int begin = _altova_mi_xs_altova_date.end ;
		public static final int end = _altova_mi_xs_altova_dateTime.begin ;
	};


	public static class _altova_mi_xs_altova_decimal {
		public static final int begin = _altova_mi_xs_altova_dateTime.end ;
		public static final int end = _altova_mi_xs_altova_decimal.begin ;
	};


	public static class _altova_mi_xs_altova_double2 {
		public static final int begin = _altova_mi_xs_altova_decimal.end ;
		public static final int end = _altova_mi_xs_altova_double2.begin ;
	};


	public static class _altova_mi_xs_altova_duration {
		public static final int begin = _altova_mi_xs_altova_double2.end ;
		public static final int end = _altova_mi_xs_altova_duration.begin ;
	};


	public static class _altova_mi_xs_altova_float2 {
		public static final int begin = _altova_mi_xs_altova_duration.end ;
		public static final int end = _altova_mi_xs_altova_float2.begin ;
	};


	public static class _altova_mi_xs_altova_gDay {
		public static final int begin = _altova_mi_xs_altova_float2.end ;
		public static final int end = _altova_mi_xs_altova_gDay.begin ;
	};


	public static class _altova_mi_xs_altova_gMonth {
		public static final int begin = _altova_mi_xs_altova_gDay.end ;
		public static final int end = _altova_mi_xs_altova_gMonth.begin ;
	};


	public static class _altova_mi_xs_altova_gMonthDay {
		public static final int begin = _altova_mi_xs_altova_gMonth.end ;
		public static final int end = _altova_mi_xs_altova_gMonthDay.begin ;
	};


	public static class _altova_mi_xs_altova_gYear {
		public static final int begin = _altova_mi_xs_altova_gMonthDay.end ;
		public static final int end = _altova_mi_xs_altova_gYear.begin ;
	};


	public static class _altova_mi_xs_altova_gYearMonth {
		public static final int begin = _altova_mi_xs_altova_gYear.end ;
		public static final int end = _altova_mi_xs_altova_gYearMonth.begin ;
	};


	public static class _altova_mi_xs_altova_hexBinary {
		public static final int begin = _altova_mi_xs_altova_gYearMonth.end ;
		public static final int end = _altova_mi_xs_altova_hexBinary.begin ;
	};


	public static class _altova_mi_xs_altova_int2 {
		public static final int begin = _altova_mi_xs_altova_hexBinary.end ;
		public static final int end = _altova_mi_xs_altova_int2.begin ;
	};


	public static class _altova_mi_xs_altova_integer {
		public static final int begin = _altova_mi_xs_altova_int2.end ;
		public static final int end = _altova_mi_xs_altova_integer.begin ;
	};


	public static class _altova_mi_xs_altova_language {
		public static final int begin = _altova_mi_xs_altova_integer.end ;
		public static final int end = _altova_mi_xs_altova_language.begin ;
	};


	public static class _altova_mi_xs_altova_long2 {
		public static final int begin = _altova_mi_xs_altova_language.end ;
		public static final int end = _altova_mi_xs_altova_long2.begin ;
	};


	public static class _altova_mi_xs_altova_negativeInteger {
		public static final int begin = _altova_mi_xs_altova_long2.end ;
		public static final int end = _altova_mi_xs_altova_negativeInteger.begin ;
	};


	public static class _altova_mi_xs_altova_nonNegativeInteger {
		public static final int begin = _altova_mi_xs_altova_negativeInteger.end ;
		public static final int end = _altova_mi_xs_altova_nonNegativeInteger.begin ;
	};


	public static class _altova_mi_xs_altova_nonPositiveInteger {
		public static final int begin = _altova_mi_xs_altova_nonNegativeInteger.end ;
		public static final int end = _altova_mi_xs_altova_nonPositiveInteger.begin ;
	};


	public static class _altova_mi_xs_altova_normalizedString {
		public static final int begin = _altova_mi_xs_altova_nonPositiveInteger.end ;
		public static final int end = _altova_mi_xs_altova_normalizedString.begin ;
	};


	public static class _altova_mi_xs_altova_positiveInteger {
		public static final int begin = _altova_mi_xs_altova_normalizedString.end ;
		public static final int end = _altova_mi_xs_altova_positiveInteger.begin ;
	};


	public static class _altova_mi_xs_altova_short2 {
		public static final int begin = _altova_mi_xs_altova_positiveInteger.end ;
		public static final int end = _altova_mi_xs_altova_short2.begin ;
	};


	public static class _altova_mi_xs_altova_string2 {
		public static final int begin = _altova_mi_xs_altova_short2.end ;
		public static final int end = _altova_mi_xs_altova_string2.begin ;
	};


	public static class _altova_mi_xs_altova_time {
		public static final int begin = _altova_mi_xs_altova_string2.end ;
		public static final int end = _altova_mi_xs_altova_time.begin ;
	};


	public static class _altova_mi_xs_altova_token {
		public static final int begin = _altova_mi_xs_altova_time.end ;
		public static final int end = _altova_mi_xs_altova_token.begin ;
	};


	public static class _altova_mi_xs_altova_unsignedByte {
		public static final int begin = _altova_mi_xs_altova_token.end ;
		public static final int end = _altova_mi_xs_altova_unsignedByte.begin ;
	};


	public static class _altova_mi_xs_altova_unsignedInt {
		public static final int begin = _altova_mi_xs_altova_unsignedByte.end ;
		public static final int end = _altova_mi_xs_altova_unsignedInt.begin ;
	};


	public static class _altova_mi_xs_altova_unsignedLong {
		public static final int begin = _altova_mi_xs_altova_unsignedInt.end ;
		public static final int end = _altova_mi_xs_altova_unsignedLong.begin ;
	};


	public static class _altova_mi_xs_altova_unsignedShort {
		public static final int begin = _altova_mi_xs_altova_unsignedLong.end ;
		public static final int end = _altova_mi_xs_altova_unsignedShort.begin ;
	};


	public static class _altova_mi_xs_altova_stringType {
		public static final int begin = _altova_mi_xs_altova_unsignedShort.end ;
		public static final int _unnamed = _altova_mi_xs_altova_stringType.begin ;
		public static final int end = 26 ;
	};


	public static class _altova_mi_xs_altova_unsignedIntType {
		public static final int begin = _altova_mi_xs_altova_stringType.end ;
		public static final int _unnamed = _altova_mi_xs_altova_unsignedIntType.begin ;
		public static final int end = 27 ;
	};

	

	public static class InfoBinder implements InfoBinderInterface
	{
		public NamespaceInfo[] getNamespaces() {return namespaces;}
		public TypeInfo[] getTypes() {return types;}
		public MemberInfo[] getMembers() {return members;}
	}
	
	public static InfoBinderInterface binder = new InfoBinder();

	// Array of all namespaces with pointers to types:
	public static final NamespaceInfo namespaces[] = 
	{
		new NamespaceInfo(binder, "http://www.drexel.edu", "", _altova_tif, _altova_til),
		new NamespaceInfo(binder, "http://www.w3.org/2001/XMLSchema", "xs", _altova_tif_xs, _altova_til_xs),
	};

	
// Array of all types with pointers to members:
	public static final TypeInfo types[] = new TypeInfoCreator().createTypes(binder);

	private static class TypeInfoCreator
	{
		private void initTypes0(InfoBinderInterface binder, TypeInfo[] types) {
			types[0] = new TypeInfo( binder, _altova_ni, "ChannelClass", _altova_ti_xs_altova_anyType, _altova_mi_altova_ChannelClass.begin, _altova_mi_altova_ChannelClass.end,  null, 				WhitespaceType.Whitespace_Unknown );
			types[1] = new TypeInfo( binder, _altova_ni, "UserClass", _altova_ti_xs_altova_anyType, _altova_mi_altova_UserClass.begin, _altova_mi_altova_UserClass.end,  null, 				WhitespaceType.Whitespace_Unknown );
			types[2] = new TypeInfo( binder, _altova_ni, "IRC", 0, _altova_mi_altova_IRC2.begin, _altova_mi_altova_IRC2.end,  null, 				WhitespaceType.Whitespace_Unknown );
			types[3] = new TypeInfo( binder, _altova_ni, "", _altova_ti_xs_altova_anyType, _altova_mi_altova_VIRCType.begin, _altova_mi_altova_VIRCType.end,  null, 				WhitespaceType.Whitespace_Unknown );
			types[4] = new TypeInfo( binder, _altova_ni, "", 0, _altova_mi_altova_CmdType.begin, _altova_mi_altova_CmdType.end,  null, 				WhitespaceType.Whitespace_Unknown, com.altova.xml.Xs.AnySimpleTypeFormatter );
			types[5] = new TypeInfo( binder, _altova_ni, "", _altova_ti_xs_altova_string2, _altova_mi_altova_CmdType2.begin, _altova_mi_altova_CmdType2.end,  
				new FacetInfo[]
				{
					new FacetInfo (com.altova.xml.XsValidation.facetCheck_string_enumeration, "enumeration", "Conn", 0 ), 
					new FacetInfo (com.altova.xml.XsValidation.facetCheck_string_enumeration, "enumeration", "Disconn", 0 ), 
					new FacetInfo (com.altova.xml.XsValidation.facetCheck_string_enumeration, "enumeration", "Join", 0 ), 
					new FacetInfo (com.altova.xml.XsValidation.facetCheck_string_enumeration, "enumeration", "Part", 0 ), 
					new FacetInfo (com.altova.xml.XsValidation.facetCheck_string_enumeration, "enumeration", "Kick", 0 ), 
					new FacetInfo (com.altova.xml.XsValidation.facetCheck_string_enumeration, "enumeration", "GetChans", 0 ), 
					new FacetInfo (com.altova.xml.XsValidation.facetCheck_string_enumeration, "enumeration", "GetUsers", 0 ), 
					new FacetInfo (com.altova.xml.XsValidation.facetCheck_string_enumeration, "enumeration", "Mute", 0 ), 
					new FacetInfo (com.altova.xml.XsValidation.facetCheck_string_enumeration, "enumeration", "Ban", 0 ), 
				},
				WhitespaceType.Whitespace_Unknown, com.altova.xml.Xs.AnySimpleTypeFormatter );
			types[6] = new TypeInfo( binder, _altova_ni, "", _altova_ti_xs_altova_anyType, _altova_mi_altova_ChansType.begin, _altova_mi_altova_ChansType.end,  null, 				WhitespaceType.Whitespace_Unknown );
			types[7] = new TypeInfo( binder, _altova_ni, "", _altova_ti_xs_altova_anyType, _altova_mi_altova_ServerType.begin, _altova_mi_altova_ServerType.end,  null, 				WhitespaceType.Whitespace_Unknown );
			types[8] = new TypeInfo( binder, _altova_ni, "", _altova_ti_xs_altova_anyType, _altova_mi_altova_UsersType.begin, _altova_mi_altova_UsersType.end,  null, 				WhitespaceType.Whitespace_Unknown );
			types[9] = new TypeInfo( binder, _altova_ni, "", _altova_ti_xs_altova_anyType, _altova_mi_altova_StatType.begin, _altova_mi_altova_StatType.end,  null, 				WhitespaceType.Whitespace_Unknown );
			types[10] = new TypeInfo( binder, _altova_ni, "", 0, _altova_mi_altova_NameType.begin, _altova_mi_altova_NameType.end,  null, 				WhitespaceType.Whitespace_Unknown, com.altova.xml.Xs.AnySimpleTypeFormatter );
			types[11] = new TypeInfo( binder, _altova_ni, "", _altova_ti_xs_altova_string2, _altova_mi_altova_NameType2.begin, _altova_mi_altova_NameType2.end,  null, 				WhitespaceType.Whitespace_Unknown, com.altova.xml.Xs.AnySimpleTypeFormatter );
			types[12] = new TypeInfo( binder, _altova_ni, "", 0, _altova_mi_altova_ModeType.begin, _altova_mi_altova_ModeType.end,  null, 				WhitespaceType.Whitespace_Unknown, com.altova.xml.Xs.AnySimpleTypeFormatter );
			types[13] = new TypeInfo( binder, _altova_ni, "", _altova_ti_xs_altova_string2, _altova_mi_altova_ModeType2.begin, _altova_mi_altova_ModeType2.end,  
				new FacetInfo[]
				{
					new FacetInfo (com.altova.xml.XsValidation.facetCheck_string_enumeration, "enumeration", "public", 0 ), 
					new FacetInfo (com.altova.xml.XsValidation.facetCheck_string_enumeration, "enumeration", "private", 0 ), 
				},
				WhitespaceType.Whitespace_Unknown, com.altova.xml.Xs.AnySimpleTypeFormatter );
			types[14] = new TypeInfo( binder, _altova_ni, "", 0, _altova_mi_altova_NickType.begin, _altova_mi_altova_NickType.end,  null, 				WhitespaceType.Whitespace_Unknown, com.altova.xml.Xs.AnySimpleTypeFormatter );
			types[15] = new TypeInfo( binder, _altova_ni, "", _altova_ti_xs_altova_string2, _altova_mi_altova_NickType2.begin, _altova_mi_altova_NickType2.end,  null, 				WhitespaceType.Whitespace_Unknown, com.altova.xml.Xs.AnySimpleTypeFormatter );

			types[16] = new TypeInfo( binder, _altova_ni_xs, "ENTITIES", _altova_ti_xs_altova_anySimpleType, _altova_mi_xs_altova_ENTITIES.begin, _altova_mi_xs_altova_ENTITIES.end,  
				new FacetInfo[]
				{
					new FacetInfo (null, "whitespace", "collapse", 0 ),
					new FacetInfo (null, "minLength", "1", 1 ), 
				},
				WhitespaceType.Whitespace_Collapse, com.altova.xml.Xs.AnySimpleTypeFormatter );
			types[17] = new TypeInfo( binder, _altova_ni_xs, "ENTITY", _altova_ti_xs_altova_NCName, _altova_mi_xs_altova_ENTITY.begin, _altova_mi_xs_altova_ENTITY.end,  null, 				WhitespaceType.Whitespace_Unknown, com.altova.xml.Xs.AnySimpleTypeFormatter );
			types[18] = new TypeInfo( binder, _altova_ni_xs, "ID", _altova_ti_xs_altova_NCName, _altova_mi_xs_altova_ID.begin, _altova_mi_xs_altova_ID.end,  null, 				WhitespaceType.Whitespace_Unknown, com.altova.xml.Xs.AnySimpleTypeFormatter );
			types[19] = new TypeInfo( binder, _altova_ni_xs, "IDREF", _altova_ti_xs_altova_NCName, _altova_mi_xs_altova_IDREF.begin, _altova_mi_xs_altova_IDREF.end,  null, 				WhitespaceType.Whitespace_Unknown, com.altova.xml.Xs.AnySimpleTypeFormatter );
			types[20] = new TypeInfo( binder, _altova_ni_xs, "IDREFS", _altova_ti_xs_altova_anySimpleType, _altova_mi_xs_altova_IDREFS.begin, _altova_mi_xs_altova_IDREFS.end,  
				new FacetInfo[]
				{
					new FacetInfo (null, "whitespace", "collapse", 0 ),
					new FacetInfo (null, "minLength", "1", 1 ), 
				},
				WhitespaceType.Whitespace_Collapse, com.altova.xml.Xs.AnySimpleTypeFormatter );
			types[21] = new TypeInfo( binder, _altova_ni_xs, "NCName", _altova_ti_xs_altova_Name, _altova_mi_xs_altova_NCName.begin, _altova_mi_xs_altova_NCName.end,  
				new FacetInfo[]
				{
					new FacetInfo (null, "pattern", "[\\i-[:]][\\c-[:]]*", 0 ), 
				},
				WhitespaceType.Whitespace_Unknown, com.altova.xml.Xs.AnySimpleTypeFormatter );
			types[22] = new TypeInfo( binder, _altova_ni_xs, "NMTOKEN", _altova_ti_xs_altova_token, _altova_mi_xs_altova_NMTOKEN.begin, _altova_mi_xs_altova_NMTOKEN.end,  
				new FacetInfo[]
				{
					new FacetInfo (null, "pattern", "\\c+", 0 ), 
				},
				WhitespaceType.Whitespace_Unknown, com.altova.xml.Xs.AnySimpleTypeFormatter );
			types[23] = new TypeInfo( binder, _altova_ni_xs, "NMTOKENS", _altova_ti_xs_altova_anySimpleType, _altova_mi_xs_altova_NMTOKENS.begin, _altova_mi_xs_altova_NMTOKENS.end,  
				new FacetInfo[]
				{
					new FacetInfo (null, "whitespace", "collapse", 0 ),
					new FacetInfo (null, "minLength", "1", 1 ), 
					new FacetInfo (null, "pattern", "\\c+", 0 ), 
					new FacetInfo (null, "pattern", "\\c+", 0 ), 
				},
				WhitespaceType.Whitespace_Collapse, com.altova.xml.Xs.AnySimpleTypeFormatter );
			types[24] = new TypeInfo( binder, _altova_ni_xs, "NOTATION", _altova_ti_xs_altova_anySimpleType, _altova_mi_xs_altova_NOTATION.begin, _altova_mi_xs_altova_NOTATION.end,  
				new FacetInfo[]
				{
					new FacetInfo (null, "whitespace", "collapse", 0 ),
				},
				WhitespaceType.Whitespace_Collapse, com.altova.xml.Xs.AnySimpleTypeFormatter );
			types[25] = new TypeInfo( binder, _altova_ni_xs, "Name", _altova_ti_xs_altova_token, _altova_mi_xs_altova_Name.begin, _altova_mi_xs_altova_Name.end,  
				new FacetInfo[]
				{
					new FacetInfo (null, "pattern", "\\i\\c*", 0 ), 
				},
				WhitespaceType.Whitespace_Unknown, com.altova.xml.Xs.AnySimpleTypeFormatter );
			types[26] = new TypeInfo( binder, _altova_ni_xs, "QName", _altova_ti_xs_altova_anySimpleType, _altova_mi_xs_altova_QName.begin, _altova_mi_xs_altova_QName.end,  
				new FacetInfo[]
				{
					new FacetInfo (null, "whitespace", "collapse", 0 ),
				},
				WhitespaceType.Whitespace_Collapse, com.altova.xml.Xs.AnySimpleTypeFormatter );
			types[27] = new TypeInfo( binder, _altova_ni_xs, "anySimpleType", 0, _altova_mi_xs_altova_anySimpleType.begin, _altova_mi_xs_altova_anySimpleType.end,  null, 				WhitespaceType.Whitespace_Unknown, com.altova.xml.Xs.AnySimpleTypeFormatter );
			types[28] = new TypeInfo( binder, _altova_ni_xs, "anyType", 0, _altova_mi_xs_altova_anyType.begin, _altova_mi_xs_altova_anyType.end,  null, 				WhitespaceType.Whitespace_Unknown, com.altova.xml.Xs.AnySimpleTypeFormatter );
			types[29] = new TypeInfo( binder, _altova_ni_xs, "anyURI", _altova_ti_xs_altova_anySimpleType, _altova_mi_xs_altova_anyURI.begin, _altova_mi_xs_altova_anyURI.end,  
				new FacetInfo[]
				{
					new FacetInfo (null, "whitespace", "collapse", 0 ),
				},
				WhitespaceType.Whitespace_Collapse, com.altova.xml.Xs.AnySimpleTypeFormatter );
			types[30] = new TypeInfo( binder, _altova_ni_xs, "base64Binary", _altova_ti_xs_altova_anySimpleType, _altova_mi_xs_altova_base64Binary.begin, _altova_mi_xs_altova_base64Binary.end,  
				new FacetInfo[]
				{
					new FacetInfo (null, "whitespace", "collapse", 0 ),
				},
				WhitespaceType.Whitespace_Collapse, com.altova.xml.Xs.AnySimpleTypeFormatter );
			types[31] = new TypeInfo( binder, _altova_ni_xs, "boolean", _altova_ti_xs_altova_anySimpleType, _altova_mi_xs_altova_boolean2.begin, _altova_mi_xs_altova_boolean2.end,  
				new FacetInfo[]
				{
					new FacetInfo (null, "whitespace", "collapse", 0 ),
				},
				WhitespaceType.Whitespace_Collapse, com.altova.xml.Xs.AnySimpleTypeFormatter );
			types[32] = new TypeInfo( binder, _altova_ni_xs, "byte", _altova_ti_xs_altova_short2, _altova_mi_xs_altova_byte2.begin, _altova_mi_xs_altova_byte2.end,  
				new FacetInfo[]
				{
					new FacetInfo (null, "minInclusive", "-128", 0 ), 
					new FacetInfo (null, "maxInclusive", "127", 0 ), 
				},
				WhitespaceType.Whitespace_Unknown, com.altova.xml.Xs.IntegerFormatter );
			types[33] = new TypeInfo( binder, _altova_ni_xs, "date", _altova_ti_xs_altova_anySimpleType, _altova_mi_xs_altova_date.begin, _altova_mi_xs_altova_date.end,  
				new FacetInfo[]
				{
					new FacetInfo (null, "whitespace", "collapse", 0 ),
				},
				WhitespaceType.Whitespace_Collapse, com.altova.xml.Xs.DateFormatter );
			types[34] = new TypeInfo( binder, _altova_ni_xs, "dateTime", _altova_ti_xs_altova_anySimpleType, _altova_mi_xs_altova_dateTime.begin, _altova_mi_xs_altova_dateTime.end,  
				new FacetInfo[]
				{
					new FacetInfo (null, "whitespace", "collapse", 0 ),
				},
				WhitespaceType.Whitespace_Collapse, com.altova.xml.Xs.DateTimeFormatter );
			types[35] = new TypeInfo( binder, _altova_ni_xs, "decimal", _altova_ti_xs_altova_anySimpleType, _altova_mi_xs_altova_decimal.begin, _altova_mi_xs_altova_decimal.end,  
				new FacetInfo[]
				{
					new FacetInfo (null, "whitespace", "collapse", 0 ),
				},
				WhitespaceType.Whitespace_Collapse, com.altova.xml.Xs.DecimalFormatter );
			types[36] = new TypeInfo( binder, _altova_ni_xs, "double", _altova_ti_xs_altova_anySimpleType, _altova_mi_xs_altova_double2.begin, _altova_mi_xs_altova_double2.end,  
				new FacetInfo[]
				{
					new FacetInfo (null, "whitespace", "collapse", 0 ),
				},
				WhitespaceType.Whitespace_Collapse, com.altova.xml.Xs.DoubleFormatter );
			types[37] = new TypeInfo( binder, _altova_ni_xs, "duration", _altova_ti_xs_altova_anySimpleType, _altova_mi_xs_altova_duration.begin, _altova_mi_xs_altova_duration.end,  
				new FacetInfo[]
				{
					new FacetInfo (null, "whitespace", "collapse", 0 ),
				},
				WhitespaceType.Whitespace_Collapse, com.altova.xml.Xs.DurationFormatter );
			types[38] = new TypeInfo( binder, _altova_ni_xs, "float", _altova_ti_xs_altova_anySimpleType, _altova_mi_xs_altova_float2.begin, _altova_mi_xs_altova_float2.end,  
				new FacetInfo[]
				{
					new FacetInfo (null, "whitespace", "collapse", 0 ),
				},
				WhitespaceType.Whitespace_Collapse, com.altova.xml.Xs.DoubleFormatter );
			types[39] = new TypeInfo( binder, _altova_ni_xs, "gDay", _altova_ti_xs_altova_anySimpleType, _altova_mi_xs_altova_gDay.begin, _altova_mi_xs_altova_gDay.end,  
				new FacetInfo[]
				{
					new FacetInfo (null, "whitespace", "collapse", 0 ),
				},
				WhitespaceType.Whitespace_Collapse, com.altova.xml.Xs.GDayFormatter );
			types[40] = new TypeInfo( binder, _altova_ni_xs, "gMonth", _altova_ti_xs_altova_anySimpleType, _altova_mi_xs_altova_gMonth.begin, _altova_mi_xs_altova_gMonth.end,  
				new FacetInfo[]
				{
					new FacetInfo (null, "whitespace", "collapse", 0 ),
				},
				WhitespaceType.Whitespace_Collapse, com.altova.xml.Xs.GMonthFormatter );
			types[41] = new TypeInfo( binder, _altova_ni_xs, "gMonthDay", _altova_ti_xs_altova_anySimpleType, _altova_mi_xs_altova_gMonthDay.begin, _altova_mi_xs_altova_gMonthDay.end,  
				new FacetInfo[]
				{
					new FacetInfo (null, "whitespace", "collapse", 0 ),
				},
				WhitespaceType.Whitespace_Collapse, com.altova.xml.Xs.GMonthDayFormatter );
			types[42] = new TypeInfo( binder, _altova_ni_xs, "gYear", _altova_ti_xs_altova_anySimpleType, _altova_mi_xs_altova_gYear.begin, _altova_mi_xs_altova_gYear.end,  
				new FacetInfo[]
				{
					new FacetInfo (null, "whitespace", "collapse", 0 ),
				},
				WhitespaceType.Whitespace_Collapse, com.altova.xml.Xs.GYearFormatter );
			types[43] = new TypeInfo( binder, _altova_ni_xs, "gYearMonth", _altova_ti_xs_altova_anySimpleType, _altova_mi_xs_altova_gYearMonth.begin, _altova_mi_xs_altova_gYearMonth.end,  
				new FacetInfo[]
				{
					new FacetInfo (null, "whitespace", "collapse", 0 ),
				},
				WhitespaceType.Whitespace_Collapse, com.altova.xml.Xs.GYearMonthFormatter );
			types[44] = new TypeInfo( binder, _altova_ni_xs, "hexBinary", _altova_ti_xs_altova_anySimpleType, _altova_mi_xs_altova_hexBinary.begin, _altova_mi_xs_altova_hexBinary.end,  
				new FacetInfo[]
				{
					new FacetInfo (null, "whitespace", "collapse", 0 ),
				},
				WhitespaceType.Whitespace_Collapse, com.altova.xml.Xs.HexBinaryFormatter );
			types[45] = new TypeInfo( binder, _altova_ni_xs, "int", _altova_ti_xs_altova_long2, _altova_mi_xs_altova_int2.begin, _altova_mi_xs_altova_int2.end,  
				new FacetInfo[]
				{
					new FacetInfo (null, "minInclusive", "-2147483648", 0 ), 
					new FacetInfo (null, "maxInclusive", "2147483647", 0 ), 
				},
				WhitespaceType.Whitespace_Unknown, com.altova.xml.Xs.IntegerFormatter );
			types[46] = new TypeInfo( binder, _altova_ni_xs, "integer", _altova_ti_xs_altova_decimal, _altova_mi_xs_altova_integer.begin, _altova_mi_xs_altova_integer.end,  
				new FacetInfo[]
				{
					new FacetInfo (null, "fractionDigits", "0", 0 ), 
					new FacetInfo (null, "pattern", "[\\-+]?[0-9]+", 0 ), 
				},
				WhitespaceType.Whitespace_Unknown, com.altova.xml.Xs.IntegerFormatter );
			types[47] = new TypeInfo( binder, _altova_ni_xs, "language", _altova_ti_xs_altova_token, _altova_mi_xs_altova_language.begin, _altova_mi_xs_altova_language.end,  
				new FacetInfo[]
				{
					new FacetInfo (null, "pattern", "[a-zA-Z]{1,8}(-[a-zA-Z0-9]{1,8})*", 0 ), 
				},
				WhitespaceType.Whitespace_Unknown, com.altova.xml.Xs.AnySimpleTypeFormatter );
			types[48] = new TypeInfo( binder, _altova_ni_xs, "long", _altova_ti_xs_altova_integer, _altova_mi_xs_altova_long2.begin, _altova_mi_xs_altova_long2.end,  
				new FacetInfo[]
				{
					new FacetInfo (null, "minInclusive", "-9223372036854775808", 0 ), 
					new FacetInfo (null, "maxInclusive", "9223372036854775807", 0 ), 
				},
				WhitespaceType.Whitespace_Unknown, com.altova.xml.Xs.IntegerFormatter );
			types[49] = new TypeInfo( binder, _altova_ni_xs, "negativeInteger", _altova_ti_xs_altova_nonPositiveInteger, _altova_mi_xs_altova_negativeInteger.begin, _altova_mi_xs_altova_negativeInteger.end,  
				new FacetInfo[]
				{
					new FacetInfo (null, "maxInclusive", "-1", 0 ), 
				},
				WhitespaceType.Whitespace_Unknown, com.altova.xml.Xs.IntegerFormatter );
			types[50] = new TypeInfo( binder, _altova_ni_xs, "nonNegativeInteger", _altova_ti_xs_altova_integer, _altova_mi_xs_altova_nonNegativeInteger.begin, _altova_mi_xs_altova_nonNegativeInteger.end,  
				new FacetInfo[]
				{
					new FacetInfo (null, "minInclusive", "0", 0 ), 
				},
				WhitespaceType.Whitespace_Unknown, com.altova.xml.Xs.IntegerFormatter );
			types[51] = new TypeInfo( binder, _altova_ni_xs, "nonPositiveInteger", _altova_ti_xs_altova_integer, _altova_mi_xs_altova_nonPositiveInteger.begin, _altova_mi_xs_altova_nonPositiveInteger.end,  
				new FacetInfo[]
				{
					new FacetInfo (null, "maxInclusive", "0", 0 ), 
				},
				WhitespaceType.Whitespace_Unknown, com.altova.xml.Xs.IntegerFormatter );
			types[52] = new TypeInfo( binder, _altova_ni_xs, "normalizedString", _altova_ti_xs_altova_string2, _altova_mi_xs_altova_normalizedString.begin, _altova_mi_xs_altova_normalizedString.end,  
				new FacetInfo[]
				{
					new FacetInfo (null, "whitespace", "replace", 0 ),
				},
				WhitespaceType.Whitespace_Replace, com.altova.xml.Xs.AnySimpleTypeFormatter );
			types[53] = new TypeInfo( binder, _altova_ni_xs, "positiveInteger", _altova_ti_xs_altova_nonNegativeInteger, _altova_mi_xs_altova_positiveInteger.begin, _altova_mi_xs_altova_positiveInteger.end,  
				new FacetInfo[]
				{
					new FacetInfo (null, "minInclusive", "1", 0 ), 
				},
				WhitespaceType.Whitespace_Unknown, com.altova.xml.Xs.IntegerFormatter );
			types[54] = new TypeInfo( binder, _altova_ni_xs, "short", _altova_ti_xs_altova_int2, _altova_mi_xs_altova_short2.begin, _altova_mi_xs_altova_short2.end,  
				new FacetInfo[]
				{
					new FacetInfo (null, "minInclusive", "-32768", 0 ), 
					new FacetInfo (null, "maxInclusive", "32767", 0 ), 
				},
				WhitespaceType.Whitespace_Unknown, com.altova.xml.Xs.IntegerFormatter );
			types[55] = new TypeInfo( binder, _altova_ni_xs, "string", _altova_ti_xs_altova_anySimpleType, _altova_mi_xs_altova_string2.begin, _altova_mi_xs_altova_string2.end,  
				new FacetInfo[]
				{
					new FacetInfo (null, "whitespace", "preserve", 0 ),
				},
				WhitespaceType.Whitespace_Preserve, com.altova.xml.Xs.AnySimpleTypeFormatter );
			types[56] = new TypeInfo( binder, _altova_ni_xs, "time", _altova_ti_xs_altova_anySimpleType, _altova_mi_xs_altova_time.begin, _altova_mi_xs_altova_time.end,  
				new FacetInfo[]
				{
					new FacetInfo (null, "whitespace", "collapse", 0 ),
				},
				WhitespaceType.Whitespace_Collapse, com.altova.xml.Xs.TimeFormatter );
			types[57] = new TypeInfo( binder, _altova_ni_xs, "token", _altova_ti_xs_altova_normalizedString, _altova_mi_xs_altova_token.begin, _altova_mi_xs_altova_token.end,  
				new FacetInfo[]
				{
					new FacetInfo (null, "whitespace", "collapse", 0 ),
				},
				WhitespaceType.Whitespace_Collapse, com.altova.xml.Xs.AnySimpleTypeFormatter );
			types[58] = new TypeInfo( binder, _altova_ni_xs, "unsignedByte", _altova_ti_xs_altova_unsignedShort, _altova_mi_xs_altova_unsignedByte.begin, _altova_mi_xs_altova_unsignedByte.end,  
				new FacetInfo[]
				{
					new FacetInfo (null, "maxInclusive", "255", 0 ), 
				},
				WhitespaceType.Whitespace_Unknown, com.altova.xml.Xs.IntegerFormatter );
			types[59] = new TypeInfo( binder, _altova_ni_xs, "unsignedInt", _altova_ti_xs_altova_unsignedLong, _altova_mi_xs_altova_unsignedInt.begin, _altova_mi_xs_altova_unsignedInt.end,  
				new FacetInfo[]
				{
					new FacetInfo (null, "maxInclusive", "4294967295", 0 ), 
				},
				WhitespaceType.Whitespace_Unknown, com.altova.xml.Xs.IntegerFormatter );
			types[60] = new TypeInfo( binder, _altova_ni_xs, "unsignedLong", _altova_ti_xs_altova_nonNegativeInteger, _altova_mi_xs_altova_unsignedLong.begin, _altova_mi_xs_altova_unsignedLong.end,  
				new FacetInfo[]
				{
					new FacetInfo (null, "maxInclusive", "18446744073709551615", 0 ), 
				},
				WhitespaceType.Whitespace_Unknown, com.altova.xml.Xs.IntegerFormatter );
			types[61] = new TypeInfo( binder, _altova_ni_xs, "unsignedShort", _altova_ti_xs_altova_unsignedInt, _altova_mi_xs_altova_unsignedShort.begin, _altova_mi_xs_altova_unsignedShort.end,  
				new FacetInfo[]
				{
					new FacetInfo (null, "maxInclusive", "65535", 0 ), 
				},
				WhitespaceType.Whitespace_Unknown, com.altova.xml.Xs.IntegerFormatter );
			types[62] = new TypeInfo( binder, _altova_ni_xs, "", 0, _altova_mi_xs_altova_stringType.begin, _altova_mi_xs_altova_stringType.end,  null, 				WhitespaceType.Whitespace_Unknown, com.altova.xml.Xs.AnySimpleTypeFormatter );
			types[63] = new TypeInfo( binder, _altova_ni_xs, "", 0, _altova_mi_xs_altova_unsignedIntType.begin, _altova_mi_xs_altova_unsignedIntType.end,  null, 				WhitespaceType.Whitespace_Unknown, com.altova.xml.Xs.IntegerFormatter );

		}

		public TypeInfo[] createTypes(InfoBinderInterface binder) {

			TypeInfo types[] = new TypeInfo[64];

			initTypes0(binder, types);
			
			return types;

		}
	}

	// Array of all members
	public static final MemberInfo members[] = new MemberInfoCreator().createMembers(binder);

	private static class MemberInfoCreator
	{
		private void initMembers0(InfoBinderInterface binder, MemberInfo[] members) {
			members[0] = new MemberInfo (binder, "http://www.drexel.edu", "Name", _altova_ti_altova_ChannelClass, _altova_ti_altova_NameType, 0, 0, 1);
			members[1] = new MemberInfo (binder, "http://www.drexel.edu", "Desc", _altova_ti_altova_ChannelClass, _altova_ti_xs_altova_stringType, 0, 0, 1);
			members[2] = new MemberInfo (binder, "http://www.drexel.edu", "Mode", _altova_ti_altova_ChannelClass, _altova_ti_altova_ModeType, 0, 0, 1);

			members[3] = new MemberInfo (binder, "http://www.drexel.edu", "Nick", _altova_ti_altova_UserClass, _altova_ti_altova_NickType, 0, 0, 1);
			members[4] = new MemberInfo (binder, "http://www.drexel.edu", "IP", _altova_ti_altova_UserClass, _altova_ti_xs_altova_stringType, 0, 0, 1);
			members[5] = new MemberInfo (binder, "http://www.drexel.edu", "Name", _altova_ti_altova_UserClass, _altova_ti_xs_altova_stringType, 0, 0, 1);
			members[6] = new MemberInfo (binder, "http://www.drexel.edu", "Pass", _altova_ti_altova_UserClass, _altova_ti_xs_altova_stringType, 0, 0, 1);

			members[7] = new MemberInfo (binder, "http://www.drexel.edu", "VIRC", _altova_ti_altova_IRC2, _altova_ti_altova_VIRCType, 0, 0, 1);

			members[8] = new MemberInfo (binder, "", "ID", _altova_ti_altova_VIRCType, _altova_ti_xs_altova_unsignedInt, 0|MemberInfo.IS_ATTRIBUTE, 0, 1);
			members[9] = new MemberInfo (binder, "", "Version", _altova_ti_altova_VIRCType, _altova_ti_xs_altova_anySimpleType, 0|MemberInfo.IS_ATTRIBUTE, 0, 1);
			members[10] = new MemberInfo (binder, "http://www.drexel.edu", "Cmd", _altova_ti_altova_VIRCType, _altova_ti_altova_CmdType, 0, 1, 1);
			members[11] = new MemberInfo (binder, "http://www.drexel.edu", "Chans", _altova_ti_altova_VIRCType, _altova_ti_altova_ChansType, 0, 0, 1);
			members[12] = new MemberInfo (binder, "http://www.drexel.edu", "Server", _altova_ti_altova_VIRCType, _altova_ti_altova_ServerType, 0, 1, 1);
			members[13] = new MemberInfo (binder, "http://www.drexel.edu", "Users", _altova_ti_altova_VIRCType, _altova_ti_altova_UsersType, 0, 0, 1);
			members[14] = new MemberInfo (binder, "http://www.drexel.edu", "Stat", _altova_ti_altova_VIRCType, _altova_ti_altova_StatType, 0, 0, 1);

			members[15] = new MemberInfo (binder, "", "", _altova_ti_altova_CmdType, _altova_ti_altova_CmdType2, 0|MemberInfo.IS_ATTRIBUTE, 1, 1);

			members[16] = new MemberInfo (binder, "http://www.drexel.edu", "Chan", _altova_ti_altova_ChansType, _altova_ti_altova_ChannelClass, 0, 1, -1);

			members[17] = new MemberInfo (binder, "http://www.drexel.edu", "IP", _altova_ti_altova_ServerType, _altova_ti_xs_altova_stringType, 0, 1, 1);

			members[18] = new MemberInfo (binder, "http://www.drexel.edu", "User", _altova_ti_altova_UsersType, _altova_ti_altova_UserClass, 0, 1, -1);

			members[19] = new MemberInfo (binder, "http://www.drexel.edu", "Msg", _altova_ti_altova_StatType, _altova_ti_xs_altova_stringType, 0, 0, 1);
			members[20] = new MemberInfo (binder, "http://www.drexel.edu", "Code", _altova_ti_altova_StatType, _altova_ti_xs_altova_unsignedIntType, 0, 0, 1);

			members[21] = new MemberInfo (binder, "", "", _altova_ti_altova_NameType, _altova_ti_altova_NameType2, 0|MemberInfo.IS_ATTRIBUTE, 1, 1);

			members[22] = new MemberInfo (binder, "", "", _altova_ti_altova_ModeType, _altova_ti_altova_ModeType2, 0|MemberInfo.IS_ATTRIBUTE, 1, 1);

			members[23] = new MemberInfo (binder, "", "", _altova_ti_altova_NickType, _altova_ti_altova_NickType2, 0|MemberInfo.IS_ATTRIBUTE, 1, 1);

			members[24] = new MemberInfo (binder, "", "", _altova_ti_xs_altova_anyType, _altova_ti_xs_altova_anySimpleType, 0|MemberInfo.IS_ATTRIBUTE, 0, -1);

			members[25] = new MemberInfo (binder, "", "", _altova_ti_xs_altova_stringType, _altova_ti_xs_altova_string2, 0|MemberInfo.IS_ATTRIBUTE, 1, 1);

			members[26] = new MemberInfo (binder, "", "", _altova_ti_xs_altova_unsignedIntType, _altova_ti_xs_altova_unsignedInt, 0|MemberInfo.IS_ATTRIBUTE, 1, 1);

		}

		public MemberInfo[] createMembers(InfoBinderInterface binder) {

			MemberInfo members[] = new MemberInfo[27];

			initMembers0(binder, members);
			
			return members;

		}
	}
}
